### ISSUE TITLE
ERRO 500

### ISSUE THREAD

**Issue by GustavoBoaz** [marianatheml/ProjetoIntegrador#9]
- [x] Alterar o max do size para 100

Ao criptografar a senha a criptografia esta maior que 60 caracteres, no formato que esta ele vai retornar 500

https://github.com/marianatheml/ProjetoIntegrador/blob/922f57d4b86cb3bbc4775c0c849bf93f677e138e/Java/src/main/java/com/projetointegrador/cultivar/model/Usuario.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L53

**Comment by marianatheml** [comment]
Corrigido como solicitado.
